project:
  type: website
  output-dir: docs
website:
  title: Recode with R
  navbar:
    search: true
    logo: "images/recode-with-r-logo.png"
    left:
    - href: index.qmd
      text: Home
    - href: course-outline.qmd
      text: Course Outline
    - href: register.qmd
      text: Register
    - href: Venue.qmd
      text: Venue      
    - href: accomodation.qmd
      text: Accomodation
    - href: about_kolkata.qmd
      text: About Kolkata
    - href: course_faculty.qmd
      text: Faculty
    - href: faq.qmd
      text: FAQs
    - href: mailto:RecodeR@tmckolkata.org
      text: Email Us
    - href: course_materials.qmd
  page-footer:
    background: dark
    left:
      - "Copyright 2023-24, Department of Radiation Oncology, Tata Medical Center, Kolkata"
    right:
      - icon: github
        href: https://github.com/drsantam
      - icon: twitter
        href: https://twitter.com/learningonco      
format:
  html:
    theme: superhero
    toc: true
    email-obfuscation: javascript
editor: visual
