project:
  type: website
  output-dir: docs
website:
  title: Recode with R
  navbar:
    left:
    - href: index.qmd
      text: Home
    - href: course-outline.qmd
      text: Course Outline
format:
  html:
    theme: superhero
    toc: true
editor: visual
