project:
  type: website
  output-dir: docs
website:
  title: Recode with R
  navbar:
    left:
    - href: index.qmd
      text: Home
    - href: course-outline.qmd
      text: Course Outline
    - href: faq.qmd
      text: FAQs
    - href: https://tmckolkata.com
      text: Register
  page-footer:
    background: dark
    left:
      - "Copyright 2023, Department of Radiation Oncology, Tata Medical Center, Kolkata"
    right:
      - icon: github
        href: https://github.com/drsantam
      - icon: twitter
        href: https://twitter.com/learningonco      
format:
  html:
    theme: superhero
    toc: true
editor: visual
