project:
  type: website
  output-dir: docs
website:
  title: Recode with R
  navbar:
    search: true
    logo: "images/recode-with-r-logo.png"
    left:
    - href: index.qmd
      text: Home
    - href: course-outline.qmd
      text: Course Outline
    - href: Venue.qmd
      text: Venue
    - href: https://tmckolkata.com
      text: Register
    - href: accomodation.qmd
      text: Accomodation
    - href: about_kolkata.qmd
      text: About Kolkata
    - href: faq.qmd
      text: FAQs
  page-footer:
    background: dark
    left:
      - "Copyright 2023-24, Department of Radiation Oncology, Tata Medical Center, Kolkata"
    right:
      - icon: github
        href: https://github.com/drsantam
      - icon: twitter
        href: https://twitter.com/learningonco      
format:
  html:
    theme: superhero
    toc: true
editor: visual
