---
title: "Recode with R Season 3"
---

# 👋 Hi

**Recode with R** - **Season 3** is back ! This time the focus is on Statistical analysis of your dataset and preparation of a statistical analysis plan. As before the course works on a BYOD principle - "Bring Your Own Data".

# 💡 Learning Objectives

-   Understand the principles of drafting a statistical analysis plan for YOUR study

-   Learning how to execute the analysis on R.

-   Learning the use of common R packages for data cleaning, visualization, and regression.

# 📔 Course Format

This time we are delivering the course online. As before this will be a closed and small group of 20 - 30 participants. Hearing the feedback we have received from the past courses, the course will be conducted over 3 Saturdays so that you can attend without disruption to your normal activities and there is sufficient time to do the required analysis.

# Prerequisites

As before we need you to bring your own dataset for analysis. We will need you also to have a laptop or computer where you can install R and the associated software. This course would not be possible on a mobile or tablet computer.

You should have the following by the start of the course:

1.  A dataset for a study which you have conducted or at least a part of the dataset.
2.  A outline of the study methodology and objectives.

# 💰 Course Fees

| Category                                             | Amount                |
|-------------------------------------------------|-----------------------|
| Permanently employed (e.g. consultants, faculty etc) | ₹ 15,000 (\~ \$180)   |
| Fellows, Registrars and Students                     | ₹ 10,000 (\~ \$ 120 ) |
| Nursing Professionals and paramedical staff          | ₹ 5,000 (\~ \$ 60)    |

: Course Fees

::: callout-caution
## Refunds

Please note that we will not be able to offer any refund of fees if you fail to notify us before 14th October 2024. You will have access to the online resources and recorded videos.
:::

The course fee includes:

1.  Unlimited access to a private repository with course materials and resources.
2.  Recordings of the course.

# 🗓️ Important Dates

**Last date of registration** **& study outline submission**: 12th September 2024

**Dates of Workshop** : 19th October to 2nd November 2024

Please note virtual contact sessions will be scheduled on:

1.  **19th October** 2024 (Saturday) 9:00 AM - 5:00 PM

2.  **26th October** 2024 (Saturday) 9:00 AM - 5:00 PM

3.  **2nd November** 2024 (Saturday) 9:00 AM - 5:00 PM

Please note that the time in between the contact sessions are reserved for your homework !

# 🏢 Conference Secretariat

Department of Radiation Oncology, Tata Medical Center, Kolkata

Phone: +91-3366058061 (ask for Mr Sougata Maity / Ms Oindrila Roy Chowdhury)

Email: RecodeR\[at\]tmckolkata\[dot\]org or santam\[dot\]chakraborty\[at\]tmckolkata\[dot\]com

# 🧑Course Coordinators

**Dr Santam Chakraborty**,

Senior Consultant, Department of Radiation Oncology, Tata Medical Center

📧 santam.chakraborty\[at\]tmckolkata\[dot\]com

**Mr Sougata Maity**

Data Imaging Scientist, Department of Radiation Oncology, Tata Medical Center

📧 maitysougata724\[at\]gmail\[dot\]com

Ms Oindrila Roy Chowdhury

Data Imaging Scientist, Department of Radiation Oncology, Tata Medical Center

📧 oindrila6176\[at\]gmail\[dot\]com
